Feat/qa deployment
Ferlab-Ste-Justine/devops pull request #9
Opened 2019-06-12 17:30 UTC by latch2112

2019-06-12 17:40 UTC, nyanofthemoon requested changes

2019-06-12 17:40 UTC, nyanofthemoon commented on Portainer/docker-compose.yml
> +      - "8080:9000"
?

2019-06-12 17:40 UTC, nyanofthemoon commented on ES/docker-compose.yml
> +      - ./esdata:/usr/share/elasticsearch/data
?

2019-06-12 17:43 UTC, latch2112 commented on Portainer/docker-compose.yml
> +      - "8080:9000"
good one

2019-06-12 17:43 UTC, latch2112 commented on ES/docker-compose.yml
> +      - ./esdata:/usr/share/elasticsearch/data
good one

2019-06-12 17:47 UTC, jecos approved these changes

2019-06-25 13:24 UTC, nyanofthemoon approved these changes
🦄

2019-06-25 13:25 UTC, merged